### PR TITLE
Replace get with head request in image check

### LINKED ISSUE #93: Replace GET with HEAD in image checks
@mattalexanderhill pointed out that doing a GET request here to check existence could potentially be improved with a HEAD:

https://github.com/EDITD/kubetools/blob/209afb1f49bf11b5f7a260140f3594c852c821e3/kubetools/deploy/image.py#L39

### PR DESCRIPTION
**Pull request by eatoncns**
Closes #93

### CODE REVIEW

**Comment by mattalexanderhill** [comment]
Reviving some stale PRs, this should be merged or closed.

**Review by mattalexanderhill — APPROVED** [review]
lgtm

**Review by ryan109 — APPROVED** [review]

**Comment by ttecles** [comment]
the thing is that Travis CI it is not building. I think @DilaraOflaz was looking into it

**Review by DilaraOflaz — APPROVED** [review]
In Travis-CI app we can see this:
```
Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/organizations/EDITD/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://app.travis-ci.com/organizations/EDITD/plan?anchor=oss-consumption).
```

So this is our current plan:
Screenshot 2022-05-27 at 12 58 59


We don't have any credit left to run build on Travis-CI.
Screenshot 2022-05-27 at 12 57 51

What is the process for that ? Do we upgrade the plan ? Or do we migrate to Jenkins ?

What is the benefit to use Travis-CI instead of Jenkins ? (For personal knowledge)

@ryan109 @gchazot

**Comment by gchazot** [comment]
This is open source software. The benefit from using TravisCI rather than private toolilng is to keep the build open source as well for transparency.

**Comment by gchazot** [comment]
I'm reaching out to TravisCI to request some OSS credits

**Comment by gchazot** [comment]
We now have some credits but:
* There is a bug that causes all  Python 3.7 build to fail. I'm working on it, no point trying to retrigger other builds until it's fixed
* We have limited free build credits on TravisCI, we need to save them, so please:
  * create a PR only once a branch is good enough to be reviewed
  * refrain from pushing commits one by one as each one triggers a build (or even 2 if a PR is open)

**Comment by gchazot** [comment]
Build bug fixed in https://github.com/EDITD/kubetools/pull/125

**Pull request merged**
